# Generated by Django 5.1.7 on 2025-04-04 06:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_idea'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaUpvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', related_query_name='upvote', to='events.idea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', related_query_name='upvote', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Idea Upvote',
                'verbose_name_plural': 'Idea Upvotes',
                'unique_together': {('idea', 'user')},
            },
        ),
    ]
